### ISSUE TITLE
TrainTutorial Error

### ISSUE THREAD

**Issue by Halmex** [Suprcheese/Orbital-Ion-Cannon#13]
Hi, found a error if I want to make a train tutorial I get the following message:
![asdasd](https://cloud.githubusercontent.com/assets/13755401/26091194/0554ece6-3a0a-11e7-9ee5-4412f9de6395.JPG)

**Comment by Suprcheese** [comment]
Huh, I didn't think to test the mini-tutorial. I'll take a look and see what's up.

**Comment by Suprcheese** [comment]
Fixed in [r126](https://github.com/Suprcheese/Orbital-Ion-Cannon/commit/e284064a22cadb9128007a2b17a423d04ada4cf8) -- thanks for the report!
