### ISSUE TITLE
Feature Request: Auto-Target only some of Ion Cannons

### ISSUE THREAD

**Issue by Rockstar04** [Suprcheese/Orbital-Ion-Cannon#14]
I'm not sure how to best implement this, but I think it would be nice if you could designate a certain number of Ion Cannons as "Manual only" and let the auto targeting use the rest of the cannons. Or make it possible to set a minimum number of cannons that need to be "ready" before auto targeting can take place?

In my current play through I had 3~4 cannons in orbit by the time I unlocked auto-targeting, but as soon as it unlocked all of the cannons were constantly being fired (understandable, its auto-targeting), but this left me with no way to focus the cannons to where I needed to expand to next, and could only let the cannons "randomly" fire where they wanted to.

**Comment by Suprcheese** [comment]
That is quite reasonable, and I've had this request before. I'll try and implement this in the next update.

**Comment by Rockstar04** [comment]
Ha, I just saw your reply on the forums. Sounds good @Supercheese, Thanks!

**Comment by Suprcheese** [comment]
Implemented in v1.5.2!
