### ISSUE TITLE
Error while running event

### ISSUE THREAD

**Issue by judos** [Suprcheese/Orbital-Ion-Cannon#15]
Hi I got this error when running the game for some time:

```
Error while running event Orbital Ion Cannon::on_biter_base_built (ID 55)
__Orbital Ion Cannon__/control.lua:196: bad argument #1 to 'pairs' (table expected, got nil)
```

Seems like it's already been reported on the modportal and you have a fix, mind to release it?
(https://mods.factorio.com/mods/Supercheese/Orbital%20Ion%20Cannon/discussion/17080)

Thanks

**Comment by Suprcheese** [comment]
Fixed in v1.5.3
