### ISSUE TITLE
Update to 0.16

### ISSUE THREAD

**Issue by sgessner** [Suprcheese/Orbital-Ion-Cannon#17]
Please update the Mod to 0.16 :)
Hopefully its just the version number to fix.

I would be very thankfull!

**Comment by Suprcheese** [comment]
I'm working on it! Got some new features in the works as well, as you can find in the commit logs: https://github.com/Suprcheese/Orbital-Ion-Cannon/commit/ae0f61e0f4807f3c4cda368c682576ca92d0a1d1

**Comment by sgessner** [comment]
I would be happy if you could schedule the 0.16 version, before you do major other changes.
I dont wanna rush you, but i would love to play it as soon as possible.
Thank you in advance!
:)

**Comment by sgessner** [comment]
I tried to get the mod to work with 0.16, but there are still some changes to do.
Please finish it.
I can not play 0.16 without this mod.
All other mods are already done.

**Comment by Suprcheese** [comment]
Update 1.6.0 released!

https://github.com/Suprcheese/Orbital-Ion-Cannon/releases/tag/1.6.0

**Comment by sgessner** [comment]
Thank you very much :) 👍 
I appreciate it a lot!
