### ISSUE TITLE
Changing config for auto-targeting doesn't have an effect. 

### ISSUE THREAD

**Issue by thundr** [Suprcheese/Orbital-Ion-Cannon#18]
No matter what the value of the 'ion-cannon-min-cannons-ready' variable, only the first two cannons ever fire on auto. Given more than 2 cannons, none of the remaining cannons get used for autofire.

**Comment by Renoh47** [comment]
Problem seems to be that the value in settings["ion-cannon-min-cannons-ready"] never gets updated with new values from mod-settings.json. Not sure if this is a problem on your (mod) end or Factorio's API

**Comment by Suprcheese** [comment]
Could not reproduce using Factorio v0.17.9.
