### ISSUE TITLE
error while running event: on_player created

### ISSUE THREAD

**Issue by IronworksProductions** [Suprcheese/Orbital-Ion-Cannon#20]
Hey i got this error when starting a new world on Factorio 16.24
Error while running event Orbital Ion Cannon::on_player_created (ID 24)
__Orbital Ion Cannon__/control.lua:107: attempt to get length of field '?' (a nil value)

Any ideas on what might be the cause?

---
NN

**Comment by Suprcheese** [comment]
Could not reproduce
