### ISSUE TITLE
Issue when used with Bob Warfare

### ISSUE THREAD

**Issue by Suprcheese** [Suprcheese/Orbital-Ion-Cannon#26]
Tech changes from Bob Warfare lead to research bug. See: https://mods.factorio.com/mod/Orbital%20Ion%20Cannon/discussion/5c864f0d74bf81000d4a952a

**Comment by emperorjimmy** [comment]
This may have been my fault, I fixed the base research but forgot the Bob's variant. At least it's an easy fix.

**Comment by Suprcheese** [comment]
Fixed in r192.
