### ISSUE TITLE
Announcer volume

### ISSUE THREAD

**Issue by emperorjimmy** [Suprcheese/Orbital-Ion-Cannon#27]
Announcer voices are muffled in map view and volume is lowered the further out you zoom, is there a way around this or is this intended?

**Comment by Suprcheese** [comment]
I think this is just something that vanilla Factorio does now in 0.17 to all sound effects.

**Comment by cgc007** [comment]
It does do this with global speakers as well. Kind of nice because if its too loud I can just zoom out instead of turning down the volume.

**Comment by Suprcheese** [comment]
As this does seem to be a base game issue, I'll close it here.
