### ISSUE TITLE
Move the detail window to player.gui.left

### ISSUE THREAD

**Issue by Nexela** [Suprcheese/Orbital-Ion-Cannon#5]
As the title suggests. Currently having the detail window open will push any Gui's (I.E Yarm, Fat Controller when open) attached to .left down the screen.  If it is moved to left side (what I term the "info" side in my GUI) it will stay closer to the same spot without moving other things down.

**Comment by Suprcheese** [comment]
Seems like a solid idea.

**Comment by Suprcheese** [comment]
Implemented in r81.
