### ISSUE TITLE
Question:  how do I change config.lua in a mod installed via portal, with Factorio running under Steam?

### ISSUE THREAD

**Issue by skandragon** [Suprcheese/Orbital-Ion-Cannon#6]

**Comment by Suprcheese** [comment]
There is a new mod configuration utility coming in Factorio 0.15 that will greatly simplify this.

For now, unzip your mod, then open up the config.lua file in the unzipped mod folder. There you will find many configuration options, as discussed in the Readme.

**Comment by skandragon** [comment]
So just unzip the file where it lives, and keep the .zip around?  Or do I need to delete it, or re-zip it with the config change?

Will the mod system keep this up to date if I unzip it?

**Comment by Suprcheese** [comment]
You can delete the .zip after you've extracted it, and leave the extracted files around.

**Comment by skandragon** [comment]
Thanks!
