### ISSUE TITLE
Cannon won't target things close by, even when they are newly discovered

### ISSUE THREAD

**Issue by skandragon** [Suprcheese/Orbital-Ion-Cannon#7]
This may be a safety thing, but I plopped down a scanner near a nest, and I expected it to take care of things, but it did not.

**Comment by Suprcheese** [comment]
Auto-targeters won't be able to target bases at point-blank range (namely, within the same chunk as the targeting station). Additionally, if you have a regular or modded radar at an outpost that provides a large region of constant-visibility, then the ATS doesn't scan the visible region, only chunks that have "Fog of War".  If this is the case, you can either clear out the close bases manually, or remove/switch off the regular radars, then the ATS should clear out any bases nearby. Once they're cleared, you can put back/switch on the regular radars once more.

**Comment by skandragon** [comment]
Gotcha, thanks!
